### ISSUE TITLE
多线程下 是不是一直是自增长的。

### ISSUE THREAD

**Issue by nodyang** [hueifeng/snowflake-csharp#1]
![image](https://user-images.githubusercontent.com/3090191/85934980-59ccb700-b91d-11ea-8e42-8f195b2e2f32.png)

我想那他当主键用 后面的要比前面的大。用于排序 但我发现了。前面比后面大的问题。是不是用的不对

**Comment by hueifeng** [comment]
@nodyang 需要使用单例模式，不然会造成重复，根据你上面这个图，是多线程下打印顺序问题，你对比一下两个时间，他是正确的

**Comment by hueifeng** [comment]
@nodyang 根据你上面这个图，是多线程下打印顺序问题，你对比一下两个时间

**Comment by nodyang** [comment]
3Q
