### ISSUE TITLE
请教个问题  望赐教 试图通过单例模式生产数据库主键 报错

### ISSUE THREAD

**Issue by nodyang** [hueifeng/snowflake-csharp#2]
![image](https://user-images.githubusercontent.com/3090191/87381586-9cea8380-c5c7-11ea-9ca1-e09d6e518b92.png)
![image](https://user-images.githubusercontent.com/3090191/87381624-b12e8080-c5c7-11ea-810d-b6bb3442328c.png)

但实际的抢购。还是有重复的订单号。望赐教

**Comment by nodyang** [comment]
测试可能分布式 dataceentid 都是1 machinedi 1 的问题

**Comment by hueifeng** [comment]
@nodyang   datacenterId和machineId对每个雪花实例应该是都不同的，在单个实例中，多线程是一个常见的场景，我们需要将雪花实例化为一个单例，实现本身的线程安全。如果说不能保证 datacenterId和machineId为单例，逻辑上就会出现重复。如果说存在很多台服务器的话那么可以通过我另外提供的高层应用接口对Redis进行集成，这样能保证运行的实例使用不同的datacenterId和machineId

**Comment by nodyang** [comment]
谢谢老哥。用redis 目前么有重复。谢谢

**Comment by hueifeng** [comment]
可以看一下使用方式，在readme中有介绍
