### ISSUE TITLE
我用net8  不生产Id cpu 暴增

### ISSUE THREAD

**Issue by nodyang** [hueifeng/snowflake-csharp#4]
Console.WriteLine("Hello, World!");
XTrace.UseConsole();

var sf = new SnowFlake(11, 2);

for (int i = 0; i < 100; i++)
{
    XTrace.WriteLine(sf.NextId().ToString());
}

**Comment by nodyang** [comment]
我退回1.30 是可以的

**Comment by nodyang** [comment]
![image](https://github.com/user-attachments/assets/0d6f477b-167c-42e0-8581-58d0530f6531)
我用源码也是这样的

**Comment by nodyang** [comment]
![image](https://github.com/user-attachments/assets/e47b7a0b-7393-4371-990d-6bcc89c9641f)
一直卡在这个地方了

**Comment by nodyang** [comment]
public virtual long NextId()
{
    while (true)
    {
        long timestamp = GetNewStamp();
        if (timestamp < _lastStamp)
        {
            // 时钟回拨，更新为上一次生成id的时间戳
            timestamp = _lastStamp;
        }

        if (_lastStamp == timestamp)
        {
            // 相同毫秒内，序列号自增
            _sequence = (_sequence + 1) & MaxSequence;
            // 同一毫秒的序列数已经达到最大
            if (_sequence == 0L)
            {
                // 等待下一个时间戳
                SpinWait.SpinUntil(() => (timestamp = GetNewStamp()) > _lastStamp);
            }
        }
        else
        {
            // 不同毫秒内，序列号置为0
            _sequence = 0L;
        }

        // 比较并更新 _lastStamp。只有在 _lastStamp 等于当前的 timestamp 时，才进行更新
        long originalLastStamp = Interlocked.CompareExchange(ref _lastStamp, timestamp, _lastStamp);
        if (originalLastStamp == _lastStamp)
        {
            // 成功更新时间戳，生成ID并返回
            return ((timestamp - StartStamp) << TimestampLeft)
                | (_datacenterId << DatacenterLeft)
                | (_machineId << MachineLeft)
                | _sequence;
        }
    }
}


我修改后 大神指点一下

**Comment by nodyang** [comment]
![image](https://github.com/user-attachments/assets/a6282649-4ce7-401e-857b-5f8a66a0e68f)
该了这个地方

**Comment by hueifeng** [comment]
可以提个PR

**Comment by nodyang** [comment]
哈哈不会。技术有点漏。还是大佬给看看
